### ISSUE TITLE
Does this work with Fabric?

### ISSUE THREAD

**Issue by Akrai** [Sqbika/AFarmK#1]
I'm using Fabric and installed this mod but i don't see any GUI or new options in the key binding config menu, or new config file, neither work any of ALT + numpad 1-9

I'm really interested in a mod that holds click for me instead of using an external program as im doing right now

**Comment by Sqbika** [comment]
The mod currently doesn't support Fabric, but I took a quick glance at Fabric (never done Fabric modding yet). It seems it's doable, but I want to research more if I can do it in same class or have to seperate Forge and Fabric class, or even if I want to approach it correctly

**Comment by Sqbika** [comment]
The port has been made. The profile keybinds are missing, but the individual toggle functionality is implemented.
I have tested it, it should be working the same way as in the 1.12.2 Forge version
A Pre-Alpha release has been made for testing purposes, you can download the fabric version there

**Comment by Akrai** [comment]
it is working properly! thank you so much! i think u can publish this release, i didnt saw bugs, and i think people will use it, add the fabric tag in the curseforge page so people can find it

**Comment by Sqbika** [comment]
The Fabric full release with profile support is released! Download it at CurseForge.
