### ISSUE TITLE
Config issues

### ISSUE THREAD

**Issue by DanShu15** [Sqbika/AFarmK#3]
![2020-06-01_10 28 45](https://user-images.githubusercontent.com/40204993/83430631-36345080-a3f3-11ea-910b-a48a49219a1c.png)

woops forgot the screenshot

I don't seem to have any mod menu options for AFarmK

also a suggestion, could you comment out some examples in the config file to go by? I have no idea how to add things to this

{
  "enableIndividual": true,
  "profiles": []
}

**Comment by Set2Minecraft** [comment]
Have the exact same issue, dont know how to fix, this is the only issue I have with this mod

**Comment by Sqbika** [comment]
Sorry for late reply.

As for the comments, in json (which is the new config format is in) doesn't support commenting. While I understand it would make it line by line clearer, it would loose the copy-paste-ability
In other branches I've defined it like this, can I get feedback if this is sufficient for understanding or should I deepen the explanation:

## Config file

Config has been reworked into a more dynamic, less restrictive format.

New example config:

```json
{
    "enableIndividual": true,
    "profiles": [
        {
            "name": "Sajt",
            "buttons": [
              "SHIFT", "LEFT_CLICK", "RIGHT_CLICK", "FORWARD", "BACKWARD", "LEFT", "RIGHT", "JUMP"
            ],
            "profileKeybind": 36
        }
    ]
}
```

**Comment by DanShu15** [comment]
That's all I needed 🙂 I prefer json anyway for datapacks, thanks for the help!

**Comment by Sqbika** [comment]
Thank you, moved 16.x branch to master and made 1.12 into it's own branch.
